// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTE3Ue1CsmWmX5-3HCGfyXoKbQh3K4BXU',
    appId: '1:768200284790:web:cbfb4ba9e4ba08668b1d57',
    messagingSenderId: '768200284790',
    projectId: 'jarceriaapp',
    authDomain: 'jarceriaapp.firebaseapp.com',
    storageBucket: 'jarceriaapp.firebasestorage.app',
    measurementId: 'G-QJJTXWLEDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Qf2A62oOjh1cGr0ODpmIFj4fs2EJn3c',
    appId: '1:768200284790:android:a3c3317987927f428b1d57',
    messagingSenderId: '768200284790',
    projectId: 'jarceriaapp',
    storageBucket: 'jarceriaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIcndUSncXygvNhjQL2HxOuV7nndb1ng',
    appId: '1:768200284790:ios:c122f4a32793c3888b1d57',
    messagingSenderId: '768200284790',
    projectId: 'jarceriaapp',
    storageBucket: 'jarceriaapp.firebasestorage.app',
    iosClientId: '768200284790-68nosub2q2qtasubc47d4ts7j1qbdg01.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarceriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIcndUSncXygvNhjQL2HxOuV7nndb1ng',
    appId: '1:768200284790:ios:c122f4a32793c3888b1d57',
    messagingSenderId: '768200284790',
    projectId: 'jarceriaapp',
    storageBucket: 'jarceriaapp.firebasestorage.app',
    iosClientId: '768200284790-68nosub2q2qtasubc47d4ts7j1qbdg01.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarceriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTE3Ue1CsmWmX5-3HCGfyXoKbQh3K4BXU',
    appId: '1:768200284790:web:eee25c3cccdc6e108b1d57',
    messagingSenderId: '768200284790',
    projectId: 'jarceriaapp',
    authDomain: 'jarceriaapp.firebaseapp.com',
    storageBucket: 'jarceriaapp.firebasestorage.app',
    measurementId: 'G-4YH7MEG975',
  );
}
